spring.datasource.url=${USER_DB_URL:jdbc:postgresql://prod-db-host:5432/user_db_prod}
spring.datasource.username=${USER_DB_USER}
spring.datasource.password=${USER_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.dynamiccarsharing=INFO