create TABLE IF NOT EXISTS disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT UNIQUE NOT NULL,
    creation_user_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('OPEN', 'RESOLVED')),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP
);