stages: [validate, build, plan, deploy]

variables:
  TF_INPUT: "false"
  TF_IN_AUTOMATION: "true"
  AWS_DEFAULT_REGION: "eu-central-1"

validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.8
    entrypoint: [""]
  script:
    - cd infra
    - rm -rf .terraform/modules
    - terraform init -backend=false -upgrade -reconfigure
    - terraform validate

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh","-c"]
  variables:
    DOCKER_CONFIG: /kaniko/.docker/
  script:
    - |
      mkdir -p /kaniko/.docker
      printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}\n' \
        "$CI_REGISTRY" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" \
        > /kaniko/.docker/config.json

      /kaniko/executor \
        --context "$CI_PROJECT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/car-service/Dockerfile" \
        --destination "$CI_REGISTRY_IMAGE/car-service:latest" \
        --destination "$CI_REGISTRY_IMAGE/car-service:${CI_COMMIT_SHA}"
  artifacts:
    when: always
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH

plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.8
    entrypoint: [""]
  script:
    - cd infra
    - rm -rf .terraform/modules
    - export AWS_ACCESS_KEY_ID=demo AWS_SECRET_ACCESS_KEY=demo AWS_EC2_METADATA_DISABLED=true
    - terraform init -backend=false -upgrade -reconfigure
    - terraform plan -refresh=false -out=tfplan.out
    - terraform show -no-color tfplan.out > tfplan.txt
  artifacts:
    paths:
      - infra/tfplan.out
      - infra/tfplan.txt
    expire_in: 1 week