services:
  db1:
    container_name: capstone-service-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./docker/initdb_app_db1.sql:/docker-entrypoint-initdb.d/initdb_app_db1.sql

  db2:
    container_name: db2_world_data
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB2_USER}
      POSTGRES_PASSWORD: ${DB2_PASSWORD}
      POSTGRES_DB: ${DB2_NAME}
    ports:
      - "${DB2_PORT}:5433"
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./docker/initdb_app_db2.sql:/docker-entrypoint-initdb.d/initdb_app_db2.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
    ports:
      - "${PGA_PORT}:80"
    depends_on:
      - db1
      - db2
volumes:
  db1_data:
    name: db1_data
  db2_data:
    name: db2_data