create DATABASE app_db1;
create DATABASE app_db2;

-- SQL queries (Capstone Project)
\c app_db1

create type car_status as ENUM ('AVAILABLE', 'RENTED', 'MAINTENANCE');
create type verification_status as ENUM ('PENDING', 'VERIFIED', 'REJECTED');
create type user_status as ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');
create type car_type as ENUM ('SEDAN', 'SUV', 'HATCHBACK', 'COUPE', 'TRUCK');
create type dispute_status as ENUM ('OPEN', 'RESOLVED');
create type payment_type as ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY');
create type user_role as ENUM ('RENTER', 'CAR_OWNER', 'ADMIN', 'GUEST');
create type transaction_status as ENUM ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED');

CREATE TABLE contact_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_info_id INT UNIQUE,
    role user_role NOT NULL,
    status user_status NOT NULL,
    FOREIGN KEY (contact_info_id) REFERENCES contact_info(id) ON DELETE CASCADE
);

CREATE TABLE location (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL
);

CREATE TABLE car (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) UNIQUE NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status car_status NOT NULL,
    location_id INT NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    type car_type NOT NULL,
    verification_status verification_status NOT NULL,
    FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE CASCADE
);

CREATE TABLE user_car (
    user_id INT NOT NULL,
    car_id INT NOT NULL,
    PRIMARY KEY (user_id, car_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE
);

CREATE TABLE booking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id INT NOT NULL,
    car_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status transaction_status NOT NULL,
    pickup_location_id INT NOT NULL,
    dispute_description VARCHAR(255),
    dispute_status dispute_status,
    FOREIGN KEY (renter_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (pickup_location_id) REFERENCES location(id) ON DELETE CASCADE
);

ALTER TABLE location
ADD COLUMN IF NOT EXISTS booking_id INT UNIQUE,
ADD CONSTRAINT fk_location_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE;

CREATE TABLE payment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    payment_method payment_type NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE dispute (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    status dispute_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE "transaction" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE car_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE user_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);

INSERT INTO contact_info (email, phone_number, first_name, last_name) VALUES
('dd.prodev@gmail.com', '+37367773888', 'Dumitru', 'Diacenco'),
('dv.prodev@gmail.com', '+37368883888', 'Vitalii', 'Diacenco'),
('rebelion.engineer@gmail.com', '+37369993999', 'Rebelion', 'Welington');

INSERT INTO "user" (contact_info_id, role, status) VALUES
(1, 'RENTER', 'ACTIVE'),
(2, 'CAR_OWNER', 'ACTIVE'),
(3, 'RENTER', 'ACTIVE');

INSERT INTO location (city, state, zip_code) VALUES
('New York', 'NY', '10001'),
('Los Angeles', 'LA', '90001'),
('Chicago', 'IL', '60601');

INSERT INTO car (registration_number, make, model, status, location_id, price_per_day, type, verification_status) VALUES
('NY123', 'Toyota', 'Camry', 'AVAILABLE', 1, 50.00, 'SEDAN', 'VERIFIED'),
('CA456', 'Honda', 'CR-V', 'AVAILABLE', 2, 70.00, 'SUV', 'VERIFIED'),
('IL789', 'Ford', 'F-150', 'RENTED', 3, 90.00, 'TRUCK', 'VERIFIED');

INSERT INTO user_car (user_id, car_id) VALUES(2, 1), (2, 2), (2, 3);

INSERT INTO booking (renter_id, car_id, start_time, end_time, status, pickup_location_id) VALUES
(1, 1, '2025-05-18 09:00:00', '2025-05-20 09:00:00', 'COMPLETED', 1),
(3, 2, '2025-05-19 10:00:00', '2025-05-21 10:00:00', 'COMPLETED', 2);

INSERT INTO payment (booking_id, amount, status, payment_method) VALUES
(1, 100.00, 'COMPLETED', 'CREDIT_CARD'),
(2, 140.00, 'COMPLETED', 'PAYPAL');

-- SQL Queries (Task: 3/4/5)
\c app_db2

create TABLE Continent(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

create TABLE Country (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    continent_id INT REFERENCES Continent(id),
    area FLOAT NOT NULL
);

create TABLE Person (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

create TABLE Person_Country (
    person_id INT REFERENCES Person(id),
    country_id INT REFERENCES Country(id),
    PRIMARY KEY (person_id, country_id)
);

INSERT INTO Continent (name) VALUES ('Europe'), ('Asia'), ('Africa'), ('North America'), ('South America'), ('Australia');

INSERT INTO Country (name, continent_id, area) VALUES
('United States', 4, 9833517),
('Sri Lanka', 2, 65610),
('Argentina', 5, 2780400),
('Germany', 1, 357582),
('Monaco', 1, 2),
('Russia', 2, 17098242),
('Brazil', 5, 8515767),
('Vatican City', 1, 0.44),
('Canada', 4, 9984670),
('Australia', 6, 7692024),
('India', 2, 3287263),
('France', 1, 643801),
('Japan', 2, 377975),
('Nigeria', 3, 923768);

INSERT INTO Person (name) VALUES ('Dumitru'), ('Rostislav'), ('Vitalii'), ('Charlie'), ('Diana'), ('Welson'),
('Raul'), ('Frank'), ('Charlie'), ('Peter'), ('Eve'), ('Dumitru'), ('Grace'), ('Alice'), ('Marius'), ('John'),
('Sarah'), ('Michael'), ('Emma'), ('David'), ('Lisa'), ('Thomas'), ('Anna'), ('Robert'), ('Julia'), ('William'),
('Sophie'), ('James'), ('Olivia'), ('Daniel'), ('Isabella'), ('Matthew'), ('Emily'), ('Andrew'), ('Charlotte'),
('Joseph'), ('Amelia'), ('Benjamin'), ('Mia'), ('Samuel'), ('Harper'), ('Alexander'), ('Evelyn'), ('Henry'),
('Abigail'), ('Edward'), ('Ella'), ('George'), ('Scarlett'), ('Charles'), ('Victoria'), ('Thomas'),
('Grace'), ('Paul'), ('Hannah'), ('Mark'), ('Lily'), ('Steven'), ('Zoe'), ('Richard'), ('Chloe');

INSERT INTO Person_Country (person_id, country_id) VALUES  (1, 1), (1, 2), (2, 3), (3, 4), (4, 1),
(4, 3), (5, 4), (5, 3), (5, 2), (6, 3), (7, 4), (8, 4), (9,4), (10,4), (16, 5), (17, 5), (18, 5),
(19, 6), (20, 6), (21, 6), (22, 7), (23, 7), (24, 7), (25, 8), (26, 8), (27, 8), (28, 9), (29, 9),
(30, 9), (31, 10), (32, 10), (33, 10), (34, 11), (35, 11), (36, 11), (37, 12), (38, 12), (39, 12),
(40, 13), (41, 13), (42, 13), (43, 14), (44, 14), (45, 14), (46, 1), (47, 2), (48, 3), (49, 4),
(50, 1), (16, 2), (17, 3), (18, 4), (19, 1), (20, 2);