CREATE TYPE car_status AS ENUM ('AVAILABLE', 'RENTED', 'MAINTENANCE');
CREATE TYPE verification_status AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');
CREATE TYPE car_type AS ENUM ('SEDAN', 'SUV', 'HATCHBACK', 'COUPE', 'TRUCK');
CREATE TYPE dispute_status AS ENUM ('OPEN', 'RESOLVED');
CREATE TYPE payment_type AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY');
CREATE TYPE user_role AS ENUM ('RENTER', 'CAR_OWNER', 'ADMIN', 'GUEST');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED');

CREATE TABLE contact_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_info_id INT UNIQUE,
    role user_role NOT NULL,
    status user_status NOT NULL,
    FOREIGN KEY (contact_info_id) REFERENCES contact_info(id) ON DELETE CASCADE
);

CREATE TABLE location (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL
);

CREATE TABLE car (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) UNIQUE NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status car_status NOT NULL,
    location_id INT NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    type car_type NOT NULL,
    verification_status verification_status NOT NULL,
    FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE CASCADE
);

CREATE TABLE user_car (
    user_id INT NOT NULL,
    car_id INT NOT NULL,
    PRIMARY KEY (user_id, car_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE
);

CREATE TABLE booking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id INT NOT NULL,
    car_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status transaction_status NOT NULL,
    pickup_location_id INT NOT NULL,
    dispute_description VARCHAR(255),
    dispute_status dispute_status,
    FOREIGN KEY (renter_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (pickup_location_id) REFERENCES location(id) ON DELETE CASCADE
);

ALTER TABLE location
ADD COLUMN IF NOT EXISTS booking_id INT UNIQUE,
ADD CONSTRAINT fk_location_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE;

CREATE TABLE payment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    payment_method payment_type NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE dispute (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    status dispute_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE "transaction" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE car_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE user_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);