CREATE TYPE car_status AS ENUM ('AVAILABLE', 'RENTED', 'MAINTENANCE');
CREATE TYPE verification_status AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');
CREATE TYPE car_type AS ENUM ('SEDAN', 'SUV', 'HATCHBACK', 'COUPE', 'TRUCK');
CREATE TYPE dispute_status AS ENUM ('OPEN', 'RESOLVED');
CREATE TYPE payment_type AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY');
CREATE TYPE user_role AS ENUM ('RENTER', 'CAR_OWNER', 'ADMIN', 'GUEST');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED');

CREATE TABLE contact_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_info_id INT UNIQUE,
    role user_role NOT NULL,
    status user_status NOT NULL,
    FOREIGN KEY (contact_info_id) REFERENCES contact_info(id) ON DELETE CASCADE
);

CREATE TABLE location (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL
);

CREATE TABLE car (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) UNIQUE NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status car_status NOT NULL,
    location_id INT NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    type car_type NOT NULL,
    verification_status verification_status NOT NULL,
    FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE CASCADE
);

CREATE TABLE user_car (
    user_id INT NOT NULL,
    car_id INT NOT NULL,
    PRIMARY KEY (user_id, car_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE
);

CREATE TABLE booking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id INT NOT NULL,
    car_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status transaction_status NOT NULL,
    pickup_location_id INT NOT NULL,
    dispute_description VARCHAR(255),
    dispute_status dispute_status,
    FOREIGN KEY (renter_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (pickup_location_id) REFERENCES location(id) ON DELETE CASCADE
);

ALTER TABLE location
ADD COLUMN IF NOT EXISTS booking_id INT UNIQUE,
ADD CONSTRAINT fk_location_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE;

CREATE TABLE payment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    payment_method payment_type NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE dispute (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    status dispute_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE "transaction" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status transaction_status NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE TABLE car_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE user_review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES "user"(id) ON DELETE CASCADE
);


INSERT INTO contact_info (email, phone_number, first_name, last_name) VALUES
('dd.prodev@gmail.com', '+37367773888', 'Dumitru', 'Diacenco'),
('dv.prodev@gmail.com', '+37368883888', 'Vitalii', 'Diacenco'),
('rebelion.engineer@gmail.com', '+37369993999', 'Rebelion', 'Welington');

INSERT INTO "user" (contact_info_id, role, status) VALUES
(1, 'RENTER', 'ACTIVE'),
(2, 'CAR_OWNER', 'ACTIVE'),
(3, 'RENTER', 'ACTIVE');

INSERT INTO location (city, state, zip_code) VALUES
('New York', 'NY', '10001'),
('Los Angeles', 'LA', '90001'),
('Chicago', 'IL', '60601');

INSERT INTO car (registration_number, make, model, status, location_id, price_per_day, type, verification_status) VALUES
('NY123', 'Toyota', 'Camry', 'AVAILABLE', 1, 50.00, 'SEDAN', 'VERIFIED'),
('CA456', 'Honda', 'CR-V', 'AVAILABLE', 2, 70.00, 'SUV', 'VERIFIED'),
('IL789', 'Ford', 'F-150', 'RENTED', 3, 90.00, 'TRUCK', 'VERIFIED');

INSERT INTO user_car (user_id, car_id) VALUES(2, 1), (2, 2), (2, 3);

INSERT INTO booking (renter_id, car_id, start_time, end_time, status, pickup_location_id) VALUES
(1, 1, '2025-05-18 09:00:00', '2025-05-20 09:00:00', 'COMPLETED', 1),
(3, 2, '2025-05-19 10:00:00', '2025-05-21 10:00:00', 'COMPLETED', 2);

INSERT INTO payment (booking_id, amount, status, payment_method) VALUES
(1, 100.00, 'COMPLETED', 'CREDIT_CARD'),
(2, 140.00, 'COMPLETED', 'PAYPAL');