server:
  port: 8085

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: car-service-route
          uri: lb://car-service
          predicates:
            - Path=/api/v1/cars/**
        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
        - id: dispute-service-route
          uri: lb://dispute-service
          predicates:
            - Path=/api/v1/disputes/**

application:
  security:
    jwt:
      secret-key: NDM0YjVmNjM1MTY0NWE3NDc3Mzg3YTMzNjE1MTQxNTg0NTUxNDg0ZjU0N2IzYjRmNmE1YjdhNmE0ZDQxNjM1Mg==
      expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
