server:
  port: ${PORT:8085}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      observation:
        enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates: [ Path=/api/v1/users/** ]
        - id: car-service-route
          uri: lb://car-service
          predicates: [ Path=/api/v1/cars/** ]
        - id: booking-service-route
          uri: lb://booking-service
          predicates: [ Path=/api/v1/bookings/** ]
        - id: dispute-service-route
          uri: lb://dispute-service
          predicates: [ Path=/api/v1/disputes/** ]

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: true

management:
  endpoints:
    web.exposure.include: "health,info,prometheus"
  endpoint.health.show-details: always
  tracing.sampling.probability: 1.0
  tracing.propagation.type: B3
  zipkin.tracing.endpoint: ${ZIPKIN_URL}