spring.datasource.url=${BOOKING_DB_URL:jdbc:postgresql://prod-db-host:5432/booking_db_prod}
spring.datasource.username=${BOOKING_DB_USER}
spring.datasource.password=${BOOKING_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.dynamiccarsharing=INFO