server:
  port: 8082

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://dynamiccarsharing_db:5432/dynamic_car_sharing_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10

  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.uuid}
    prefer-ip-address: false
    hostname: booking-service
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  cloud:
    loadbalancer:
      enabled: true
      retry:
        enabled: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.client.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: ${server.port}