spring.application.name=DynamicCarSharing

# Set the default profile to 'local'. This means if you don't specify another profile, Spring will load application-local.properties.
spring.profiles.active=local

logging.level.com.dynamiccarsharing=DEBUG
logging.level.org.springframework.jdbc=DEBUG

spring.jpa.hibernate.ddl-auto=update