create TABLE IF NOT EXISTS contact_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_info_id BIGINT UNIQUE,
    role VARCHAR(50) NOT NULL CHECK (role IN ('RENTER', 'CAR_OWNER', 'ADMIN', 'GUEST')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'BANNED')),
    CONSTRAINT fk_users_on_contact_infos FOREIGN KEY (contact_info_id) REFERENCES contact_infos(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL
);

create TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) UNIQUE NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('AVAILABLE', 'RENTED', 'MAINTENANCE')),
    location_id BIGINT NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('SEDAN', 'SUV', 'HATCHBACK', 'COUPE', 'TRUCK')),
    verification_status VARCHAR(50) NOT NULL CHECK (verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT fk_cars_on_locations FOREIGN KEY (location_id) REFERENCES locations(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS user_cars (
    user_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, car_id),
    CONSTRAINT fk_user_cars_on_users FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
    CONSTRAINT fk_user_cars_on_cars FOREIGN KEY (car_id) REFERENCES cars(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    pickup_location_id BIGINT NOT NULL,
    dispute_description VARCHAR(255),
    dispute_status VARCHAR(50) CHECK (dispute_status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT fk_bookings_on_users FOREIGN KEY (renter_id) REFERENCES users(id) ON delete CASCADE,
    CONSTRAINT fk_bookings_on_cars FOREIGN KEY (car_id) REFERENCES cars(id) ON delete CASCADE,
    CONSTRAINT fk_bookings_on_locations FOREIGN KEY (pickup_location_id) REFERENCES locations(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payments_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT UNIQUE NOT NULL,
    creation_user_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('OPEN', 'RESOLVED')),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_disputes_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE,
    CONSTRAINT fk_disputes_on_users FOREIGN KEY (creation_user_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_transactions_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS car_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    CONSTRAINT fk_car_reviews_on_cars FOREIGN KEY (car_id) REFERENCES cars(id) ON delete CASCADE,
    CONSTRAINT fk_car_reviews_on_users FOREIGN KEY (reviewer_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS user_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_reviews_on_users_user FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
    CONSTRAINT fk_user_reviews_on_users_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON delete CASCADE
);