spring.datasource.url=${CAR_DB_URL:jdbc:postgresql://prod-db-host:5432/car_db_prod}
spring.datasource.username=${CAR_DB_USER}
spring.datasource.password=${CAR_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.dynamiccarsharing=INFO