spring.application.name=car-service

# Run locally: JDBC DAO implementation
# spring.profiles.active=local,jdbc

# Run locally: Spring Data JPA implementation
spring.profiles.active=local,jpa

logging.level.com.dynamiccarsharing=DEBUG
logging.level.org.springframework.jdbc=DEBUG

spring.jpa.hibernate.ddl-auto=update

service.user.url=${USER_SERVICE_URL:http://localhost:8080/api/users}
service.booking.url=${BOOKING_SERVICE_URL:http://localhost:8082/api/bookings}