server.port=8083
spring.application.name=dispute-service
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=dispute-service-app
spring.profiles.active=local,jpa
logging.level.com.dynamiccarsharing=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.jpa.hibernate.ddl-auto=update
# Database configuration (can be overridden by environment variables)
spring.datasource.url=jdbc:postgresql://dynamiccarsharing_db:5432/dynamiccarsharing
spring.datasource.username=postgres
spring.datasource.password=postgres