

create TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    pickup_location_id BIGINT NOT NULL,
    promo_code VARCHAR(255)
);

create TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    cancellation_penalty_amount DECIMAL(10, 2),
    cancellation_refund_amount DECIMAL(10, 2),
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payments_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS booking_lifecycle_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

create TABLE IF NOT EXISTS booking_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    body VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_booking_messages_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS booking_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    pickup_location_id BIGINT NOT NULL,
    promo_code VARCHAR(255),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE', 'CANCELED', 'PROMOTED')),
    created_at TIMESTAMP NOT NULL
);

create TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'COMPLETED', 'CANCELED')),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'MOBILE_MONEY')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_transactions_on_bookings FOREIGN KEY (booking_id) REFERENCES bookings(id) ON delete CASCADE
);