spring.datasource.url=jdbc:postgresql://localhost:5432/car_db_dev
spring.datasource.username=dev_user
spring.datasource.password=dev_secret_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect