create TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL
);

create TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) UNIQUE NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('AVAILABLE', 'RENTED', 'MAINTENANCE')),
    location_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('SEDAN', 'SUV', 'HATCHBACK', 'COUPE', 'TRUCK')),
    verification_status VARCHAR(50) NOT NULL CHECK (verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    average_rating DECIMAL(4, 2),
    review_count INTEGER,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_cars_on_locations FOREIGN KEY (location_id) REFERENCES locations(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS car_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    booking_id BIGINT,
    rating INTEGER,
    comment VARCHAR(255) NOT NULL,
    CONSTRAINT fk_car_reviews_on_cars FOREIGN KEY (car_id) REFERENCES cars(id) ON delete CASCADE,
    CONSTRAINT uk_car_reviews_booking_id UNIQUE (booking_id)
);