create TABLE IF NOT EXISTS contact_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_info_id BIGINT UNIQUE,
    role VARCHAR(50) NOT NULL CHECK (role IN ('RENTER', 'CAR_OWNER', 'ADMIN', 'GUEST')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'BANNED')),
    referral_code VARCHAR(32) UNIQUE,
    referred_by_user_id BIGINT,
    CONSTRAINT fk_users_on_contact_infos FOREIGN KEY (contact_info_id) REFERENCES contact_infos(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS user_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_reviews_on_users_user FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
    CONSTRAINT fk_user_reviews_on_users_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON delete CASCADE
);